# Generated by Django 6.0.2 on 2026-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('organizer', 'Event Organizer'), ('staff', 'Gate Staff'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee')], default='attendee', max_length=20),
        ),
    ]
