# Generated by Django 6.0.3 on 2026-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('organizer', 'Event Organizer'), ('staff', 'Gate Staff'), ('usher', 'Usher'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('attendee', 'Attendee')], default='attendee', max_length=20),
        ),
    ]
