# Generated by Django 6.0.3 on 2026-03-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(help_text='Hex color code', max_length=7)),
                ('neutral_light', models.CharField(help_text='Hex color code', max_length=7)),
                ('neutral_dark', models.CharField(help_text='Hex color code', max_length=7)),
                ('css_content', models.TextField(help_text='Generated CSS theme content')),
                ('css_hash', models.CharField(help_text='SHA-256 hash for caching', max_length=64, unique=True)),
                ('extraction_confidence', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('is_fallback', models.BooleanField(default=False, help_text='Whether fallback theme was used')),
                ('generation_method', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('fallback', 'Fallback')], default='auto', max_length=50)),
                ('wcag_compliant', models.BooleanField(default=True, help_text='WCAG 2.1 AA compliant')),
                ('contrast_adjustments_made', models.BooleanField(default=False, help_text='Colors adjusted for accessibility')),
                ('cache_key', models.CharField(help_text='Unique cache identifier', max_length=100, unique=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Theme',
                'verbose_name_plural': 'Event Themes',
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_colors', models.JSONField(default=list, help_text='List of extracted colors with confidence and frequency data')),
                ('source_image', models.CharField(help_text='Path to source image', max_length=255)),
                ('extraction_algorithm', models.CharField(choices=[('kmeans', 'K-Means Clustering'), ('colorthief', 'Color Thief'), ('dominant', 'Dominant Color'), ('manual', 'Manual Selection')], default='kmeans', max_length=50)),
                ('extraction_parameters', models.JSONField(default=dict, help_text='Algorithm parameters used')),
                ('color_diversity_score', models.FloatField(default=0.0, help_text='Color diversity score 0-1')),
                ('overall_confidence', models.FloatField(default=0.0, help_text='Overall extraction confidence 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='palette', to='theming.eventtheme')),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
            },
        ),
        migrations.CreateModel(
            name='ThemeCache',
            fields=[
                ('cache_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('css_content', models.TextField(help_text='Cached CSS content')),
                ('portal_type', models.CharField(choices=[('staff', 'Staff Portal'), ('participant', 'Participant Portal'), ('organizer', 'Organizer Portal'), ('universal', 'Universal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='theming.eventtheme')),
            ],
            options={
                'verbose_name': 'Theme Cache',
                'verbose_name_plural': 'Theme Cache Entries',
            },
        ),
        migrations.CreateModel(
            name='ThemeGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('generation', 'Theme Generation'), ('fallback', 'Fallback Applied'), ('manual_override', 'Manual Override'), ('cache_hit', 'Cache Hit'), ('cache_miss', 'Cache Miss'), ('accessibility_fix', 'Accessibility Fix'), ('variation_created', 'Variation Created')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial Success'), ('warning', 'Warning')], max_length=20)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if operation failed')),
                ('extraction_confidence', models.FloatField(blank=True, help_text='Color extraction confidence', null=True)),
                ('source_image_path', models.CharField(blank=True, help_text='Path to source image', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional operation metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_logs', to='events.event')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Generation Log',
                'verbose_name_plural': 'Theme Generation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('high_contrast', 'High Contrast'), ('colorblind_friendly', 'Colorblind Friendly'), ('minimal', 'Minimal'), ('vibrant', 'Vibrant')], max_length=50)),
                ('css_content', models.TextField(help_text='CSS content for this variation')),
                ('css_hash', models.CharField(help_text='SHA-256 hash for caching', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='theming.eventtheme')),
            ],
            options={
                'verbose_name': 'Theme Variation',
                'verbose_name_plural': 'Theme Variations',
            },
        ),
        migrations.AddIndex(
            model_name='eventtheme',
            index=models.Index(fields=['css_hash'], name='theming_eve_css_has_0fcf44_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtheme',
            index=models.Index(fields=['cache_key'], name='theming_eve_cache_k_3f6509_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtheme',
            index=models.Index(fields=['last_accessed'], name='theming_eve_last_ac_99430c_idx'),
        ),
        migrations.AddIndex(
            model_name='themecache',
            index=models.Index(fields=['expires_at'], name='theming_the_expires_cb3e45_idx'),
        ),
        migrations.AddIndex(
            model_name='themecache',
            index=models.Index(fields=['last_accessed'], name='theming_the_last_ac_28d0de_idx'),
        ),
        migrations.AddIndex(
            model_name='themecache',
            index=models.Index(fields=['portal_type'], name='theming_the_portal__e8e992_idx'),
        ),
        migrations.AddIndex(
            model_name='themegenerationlog',
            index=models.Index(fields=['created_at'], name='theming_the_created_e8594c_idx'),
        ),
        migrations.AddIndex(
            model_name='themegenerationlog',
            index=models.Index(fields=['status'], name='theming_the_status_9679de_idx'),
        ),
        migrations.AddIndex(
            model_name='themegenerationlog',
            index=models.Index(fields=['operation_type'], name='theming_the_operati_ca33fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='themevariation',
            unique_together={('base_theme', 'variation_type')},
        ),
    ]
