# Generated by Django 6.0.2 on 2026-03-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_speaker_eventsession_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='Team Member', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='events.event')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
