# Generated by Django 6.0.3 on 2026-03-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventteamassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTeamAssignment',
        ),
    ]
