# Generated by Django 6.0.3 on 2026-03-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_profile_picture', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('speaker_bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_sessions', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
