# Generated by Django 6.0.3 on 2026-03-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
        ('events', '0005_event_views_count'),
    ]

    operations = [
    ]
