# Generated by Django 6.0.3 on 2026-03-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_bio', models.TextField(blank=True, null=True)),
                ('speaker_profile_picture', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('speaking_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('individual_start_time', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_speakers', to='events.session')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
