# Generated by Django 6.0.3 on 2026-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_session_session_end_time_session_session_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionspeaker',
            name='individual_start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='speaker_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speaker_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionspeaker',
            name='speaker_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionspeaker',
            name='speaker_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
