# Generated by Django 6.0.3 on 2026-03-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_accent_color_event_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_profile_picture', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('speaker_bio', models.TextField(blank=True)),
                ('session_start_time', models.DateTimeField(blank=True, null=True)),
                ('session_end_time', models.DateTimeField(blank=True, null=True)),
                ('speaker_start_time', models.TimeField(blank=True, null=True)),
                ('speaker_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_sessions', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_bio', models.TextField(blank=True, null=True)),
                ('speaker_profile_picture', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('speaker_start_time', models.TimeField(blank=True, null=True)),
                ('speaker_end_time', models.TimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_speakers', to='events.session')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
