# Generated by Django 6.0.3 on 2026-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_sessionspeaker_individual_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionspeaker',
            name='speaking_duration',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
