# Generated by Django 6.0.3 on 2026-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_session_sessionspeaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='sessionspeaker',
            name='speaker_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
