# Generated by Django 6.0.2 on 2026-03-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_merge_0005_alter_event_status_0005_event_views_count'),
        ('events', '0009_remove_sessionspeaker_speaking_duration_and_more'),
    ]

    operations = [
    ]
