$basePath = "c:\Users\zefasil\Desktop\cloning to test and work my part\Intern-project"

$excludeDirs = @('.git', '.venv', 'venv', 'node_modules', '__pycache__', 'media', 'static', 'advanced - Copy')

# Only target the apps with remaining issues
$targetDirs = @('advanced', 'coordinator', 'events', 'organizer', 'users', 'theming', 'registration')

Get-ChildItem -Path $basePath -Recurse -Filter *.html | Where-Object {
    $path = $_.FullName
    
    $inTargetDir = $false
    foreach ($dir in $targetDirs) {
        if ($path -match "\\$dir\\templates\\") { $inTargetDir = $true; break }
    }
    
    $skip = $false
    foreach ($dir in $excludeDirs) {
        if ($path -match "\\$dir\\") { $skip = $true; break }
    }

    $inTargetDir -and -not $skip
} | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    $original = $content

    $updates = 0

    # 1. Colors Migration (Indigo to Primary/Semantic)
    $content = $content -replace 'bg-indigo-600 hover:bg-indigo-700', 'bg-primary hover:bg-primary-dark transition-colors'
    $content = $content -replace 'bg-indigo-600', 'bg-primary'
    $content = $content -replace 'text-indigo-600 hover:text-indigo-500', 'text-primary hover:text-primary-dark transition-colors'
    $content = $content -replace 'text-indigo-600', 'text-primary'
    $content = $content -replace 'text-indigo-700', 'text-primary-dark'
    $content = $content -replace 'bg-indigo-50', 'bg-primary/5'
    $content = $content -replace 'bg-indigo-100', 'bg-primary/10'
    $content = $content -replace 'border-indigo-500', 'border-primary'
    $content = $content -replace 'border-indigo-600', 'border-primary'
    $content = $content -replace 'border-indigo-200', 'border-primary/20'
    $content = $content -replace 'focus:ring-indigo-500', 'focus:ring-primary'
    $content = $content -replace 'focus:border-indigo-500', 'focus:border-primary'

    # Same for generic blue
    $content = $content -replace 'bg-blue-600 hover:bg-blue-700', 'bg-primary hover:bg-primary-dark transition-colors'
    $content = $content -replace 'bg-blue-600', 'bg-primary'
    $content = $content -replace 'text-blue-600 hover:text-blue-500', 'text-primary hover:text-primary-dark transition-colors'
    $content = $content -replace 'text-blue-600 hover:text-blue-700', 'text-primary hover:text-primary-dark transition-colors'
    $content = $content -replace 'text-blue-600', 'text-primary'
    $content = $content -replace 'bg-blue-50', 'bg-primary/5'

    # Update complex Tailwind button strings to standard semantic ea-btn
    $content = $content -replace 'class="[^"]*inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-primary hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary[^"]*"', 'class="ea-btn ea-btn-primary"'
    $content = $content -replace 'class="[^"]*inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-primary hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary[^"]*"', 'class="ea-btn ea-btn-primary"'
    $content = $content -replace 'class="[^"]*w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary[^"]*"', 'class="ea-btn ea-btn-primary w-full"'
    
    # Generic specific button patterns
    $content = $content -replace 'class="[A-Za-z0-s\-_]*bg-primary text-white[A-Za-z0-s\-_]*"', 'class="ea-btn ea-btn-primary"'

    # 4. Font Awesome to Bootstrap Icons Migration
    # Solid
    $content = $content -replace 'fas fa-arrow-left', 'bi bi-arrow-left'
    $content = $content -replace 'fas fa-arrow-right', 'bi bi-arrow-right'
    $content = $content -replace 'fas fa-arrow-up', 'bi bi-arrow-up'
    $content = $content -replace 'fas fa-arrow-down', 'bi bi-arrow-down'
    $content = $content -replace 'fas fa-check-circle', 'bi bi-check-circle-fill'
    $content = $content -replace 'fas fa-check', 'bi bi-check-lg'
    $content = $content -replace 'fas fa-times-circle', 'bi bi-x-circle-fill'
    $content = $content -replace 'fas fa-times', 'bi bi-x-lg'
    $content = $content -replace 'fas fa-exclamation-circle', 'bi bi-exclamation-circle-fill'
    $content = $content -replace 'fas fa-exclamation-triangle', 'bi bi-exclamation-triangle-fill'
    $content = $content -replace 'fas fa-info-circle', 'bi bi-info-circle-fill'
    $content = $content -replace 'fas fa-calendar-alt', 'bi bi-calendar-event'
    $content = $content -replace 'fas fa-calendar-plus', 'bi bi-calendar-plus'
    $content = $content -replace 'fas fa-calendar-check', 'bi bi-calendar-check'
    $content = $content -replace 'fas fa-clock', 'bi bi-clock'
    $content = $content -replace 'fas fa-map-marker-alt', 'bi bi-geo-alt-fill'
    $content = $content -replace 'fas fa-ticket-alt', 'bi bi-ticket-perforated'
    $content = $content -replace 'fas fa-ticket', 'bi bi-ticket-perforated'
    $content = $content -replace 'fas fa-user-circle', 'bi bi-person-circle'
    $content = $content -replace 'fas fa-user-cog', 'bi bi-person-gear'
    $content = $content -replace 'fas fa-user-edit', 'bi bi-person-lines-fill'
    $content = $content -replace 'fas fa-user-plus', 'bi bi-person-plus-fill'
    $content = $content -replace 'fas fa-user-lock', 'bi bi-person-lock'
    $content = $content -replace 'fas fa-user-shield', 'bi bi-person-badge'
    $content = $content -replace 'fas fa-users-cog', 'bi bi-people-fill'
    $content = $content -replace 'fas fa-users', 'bi bi-people-fill'
    $content = $content -replace 'fas fa-user', 'bi bi-person-fill'
    $content = $content -replace 'fas fa-cog', 'bi bi-gear-fill'
    $content = $content -replace 'fas fa-cogs', 'bi bi-gear-wide-connected'
    $content = $content -replace 'fas fa-wrench', 'bi bi-wrench'
    $content = $content -replace 'fas fa-tachometer-alt', 'bi bi-speedometer2'
    $content = $content -replace 'fas fa-chart-line', 'bi bi-graph-up'
    $content = $content -replace 'fas fa-chart-bar', 'bi bi-bar-chart-fill'
    $content = $content -replace 'fas fa-chart-pie', 'bi bi-pie-chart-fill'
    $content = $content -replace 'fas fa-home', 'bi bi-house-door-fill'
    $content = $content -replace 'fas fa-envelope', 'bi bi-envelope-fill'
    $content = $content -replace 'fas fa-envelope-open-text', 'bi bi-envelope-open-fill'
    $content = $content -replace 'fas fa-paper-plane', 'bi bi-send-fill'
    $content = $content -replace 'fas fa-bell', 'bi bi-bell-fill'
    $content = $content -replace 'fas fa-search', 'bi bi-search'
    $content = $content -replace 'fas fa-plus-circle', 'bi bi-plus-circle-fill'
    $content = $content -replace 'fas fa-plus', 'bi bi-plus-lg'
    $content = $content -replace 'fas fa-trash-alt', 'bi bi-trash-fill'
    $content = $content -replace 'fas fa-trash', 'bi bi-trash-fill'
    $content = $content -replace 'fas fa-edit', 'bi bi-pencil-square'
    $content = $content -replace 'fas fa-pencil-alt', 'bi bi-pencil-fill'
    $content = $content -replace 'fas fa-save', 'bi bi-floppy-fill'
    $content = $content -replace 'fas fa-download', 'bi bi-download'
    $content = $content -replace 'fas fa-upload', 'bi bi-upload'
    $content = $content -replace 'fas fa-print', 'bi bi-printer-fill'
    $content = $content -replace 'fas fa-file-pdf', 'bi bi-file-earmark-pdf-fill'
    $content = $content -replace 'fas fa-file-excel', 'bi bi-file-earmark-excel-fill'
    $content = $content -replace 'fas fa-file-alt', 'bi bi-file-earmark-text-fill'
    $content = $content -replace 'fas fa-file', 'bi bi-file-earmark-fill'
    $content = $content -replace 'fas fa-image', 'bi bi-image-fill'
    $content = $content -replace 'fas fa-video', 'bi bi-camera-video-fill'
    $content = $content -replace 'fas fa-camera', 'bi bi-camera-fill'
    $content = $content -replace 'fas fa-link', 'bi bi-link-45deg'
    $content = $content -replace 'fas fa-external-link-alt', 'bi bi-box-arrow-up-right'
    $content = $content -replace 'fas fa-share-alt', 'bi bi-share-fill'
    $content = $content -replace 'fas fa-share', 'bi bi-share-fill'
    $content = $content -replace 'fas fa-copy', 'bi bi-clipboard-fill'
    $content = $content -replace 'fas fa-clipboard-list', 'bi bi-clipboard2-data-fill'
    $content = $content -replace 'fas fa-list-alt', 'bi bi-card-list'
    $content = $content -replace 'fas fa-list-ul', 'bi bi-list-ul'
    $content = $content -replace 'fas fa-list-ol', 'bi bi-list-ol'
    $content = $content -replace 'fas fa-th-large', 'bi bi-grid-fill'
    $content = $content -replace 'fas fa-th-list', 'bi bi-view-list'
    $content = $content -replace 'fas fa-th', 'bi bi-grid-3x3-gap-fill'
    $content = $content -replace 'fas fa-bars', 'bi bi-list'
    $content = $content -replace 'fas fa-ellipsis-v', 'bi bi-three-dots-vertical'
    $content = $content -replace 'fas fa-ellipsis-h', 'bi bi-three-dots'
    $content = $content -replace 'fas fa-spinner fa-spin', 'bi bi-arrow-repeat ea-spin'
    $content = $content -replace 'fas fa-circle-notch fa-spin', 'bi bi-arrow-repeat ea-spin'
    $content = $content -replace 'fas fa-sync-alt fa-spin', 'bi bi-arrow-repeat ea-spin'
    $content = $content -replace 'fas fa-sync-alt', 'bi bi-arrow-repeat'
    $content = $content -replace 'fas fa-sync', 'bi bi-arrow-repeat'
    $content = $content -replace 'fas fa-redo', 'bi bi-arrow-clockwise'
    $content = $content -replace 'fas fa-undo', 'bi bi-arrow-counterclockwise'
    $content = $content -replace 'fas fa-chevron-right', 'bi bi-chevron-right'
    $content = $content -replace 'fas fa-chevron-left', 'bi bi-chevron-left'
    $content = $content -replace 'fas fa-chevron-down', 'bi bi-chevron-down'
    $content = $content -replace 'fas fa-chevron-up', 'bi bi-chevron-up'
    $content = $content -replace 'fas fa-angle-right', 'bi bi-chevron-right'
    $content = $content -replace 'fas fa-angle-left', 'bi bi-chevron-left'
    $content = $content -replace 'fas fa-angle-down', 'bi bi-chevron-down'
    $content = $content -replace 'fas fa-angle-up', 'bi bi-chevron-up'
    $content = $content -replace 'fas fa-caret-down', 'bi bi-caret-down-fill'
    $content = $content -replace 'fas fa-caret-up', 'bi bi-caret-up-fill'
    $content = $content -replace 'fas fa-caret-right', 'bi bi-caret-right-fill'
    $content = $content -replace 'fas fa-caret-left', 'bi bi-caret-left-fill'
    $content = $content -replace 'fas fa-crown', 'bi bi-award-fill'
    $content = $content -replace 'fas fa-star', 'bi bi-star-fill'
    $content = $content -replace 'fas fa-star-half-alt', 'bi bi-star-half'
    $content = $content -replace 'fas fa-heart', 'bi bi-heart-fill'
    $content = $content -replace 'fas fa-thumbs-up', 'bi bi-hand-thumbs-up-fill'
    $content = $content -replace 'fas fa-thumbs-down', 'bi bi-hand-thumbs-down-fill'
    $content = $content -replace 'fas fa-comment', 'bi bi-chat-fill'
    $content = $content -replace 'fas fa-comment-dots', 'bi bi-chat-dots-fill'
    $content = $content -replace 'fas fa-comments', 'bi bi-chat-text-fill'
    $content = $content -replace 'fas fa-microphone', 'bi bi-mic-fill'
    $content = $content -replace 'fas fa-microphone-slash', 'bi bi-mic-mute-fill'
    $content = $content -replace 'fas fa-volume-up', 'bi bi-volume-up-fill'
    $content = $content -replace 'fas fa-volume-mute', 'bi bi-volume-mute-fill'
    $content = $content -replace 'fas fa-lock', 'bi bi-lock-fill'
    $content = $content -replace 'fas fa-unlock', 'bi bi-unlock-fill'
    $content = $content -replace 'fas fa-key', 'bi bi-key-fill'
    $content = $content -replace 'fas fa-shield-alt', 'bi bi-shield-lock-fill'
    $content = $content -replace 'fas fa-sign-in-alt', 'bi bi-box-arrow-in-right'
    $content = $content -replace 'fas fa-sign-out-alt', 'bi bi-box-arrow-right'
    $content = $content -replace 'fas fa-door-open', 'bi bi-door-open-fill'
    $content = $content -replace 'fas fa-building', 'bi bi-building'
    $content = $content -replace 'fas fa-briefcase', 'bi bi-briefcase-fill'
    $content = $content -replace 'fas fa-id-badge', 'bi bi-person-badge-fill'
    $content = $content -replace 'fas fa-id-card', 'bi bi-person-vcard-fill'
    $content = $content -replace 'fas fa-tags', 'bi bi-tags-fill'
    $content = $content -replace 'fas fa-tag', 'bi bi-tag-fill'
    $content = $content -replace 'fas fa-bookmark', 'bi bi-bookmark-fill'
    $content = $content -replace 'fas fa-map', 'bi bi-map-fill'
    $content = $content -replace 'fas fa-compass', 'bi bi-compass-fill'
    $content = $content -replace 'fas fa-globe', 'bi bi-globe'
    $content = $content -replace 'fas fa-sitemap', 'bi bi-diagram-3-fill'
    $content = $content -replace 'fas fa-network-wired', 'bi bi-hdd-network-fill'
    $content = $content -replace 'fas fa-server', 'bi bi-server'
    $content = $content -replace 'fas fa-database', 'bi bi-database-fill'
    $content = $content -replace 'fas fa-hdd', 'bi bi-hdd-fill'
    $content = $content -replace 'fas fa-laptop', 'bi bi-laptop-fill'
    $content = $content -replace 'fas fa-mobile-alt', 'bi bi-phone-fill'
    $content = $content -replace 'fas fa-tablet-alt', 'bi bi-tablet-fill'
    $content = $content -replace 'fas fa-desktop', 'bi bi-display-fill'
    $content = $content -replace 'fas fa-qrcode', 'bi bi-qr-code'
    $content = $content -replace 'fas fa-barcode', 'bi bi-upc-scan'
    $content = $content -replace 'fas fa-shopping-cart', 'bi bi-cart-fill'
    $content = $content -replace 'fas fa-cart-plus', 'bi bi-cart-plus-fill'
    $content = $content -replace 'fas fa-credit-card', 'bi bi-credit-card-fill'
    $content = $content -replace 'fas fa-money-bill-wave', 'bi bi-cash-stack'
    $content = $content -replace 'fas fa-coins', 'bi bi-coin'
    $content = $content -replace 'fas fa-wallet', 'bi bi-wallet-fill'
    $content = $content -replace 'fas fa-dollar-sign', 'bi bi-currency-dollar'
    $content = $content -replace 'fas fa-euro-sign', 'bi bi-currency-euro'
    $content = $content -replace 'fas fa-pound-sign', 'bi bi-currency-pound'
    $content = $content -replace 'fas fa-yen-sign', 'bi bi-currency-yen'
    $content = $content -replace 'fas fa-percent', 'bi bi-percent'
    $content = $content -replace 'fas fa-receipt', 'bi bi-receipt'
    $content = $content -replace 'fas fa-file-invoice-dollar', 'bi bi-file-earmark-ruled-fill'
    $content = $content -replace 'fas fa-gift', 'bi bi-gift-fill'
    $content = $content -replace 'fas fa-box', 'bi bi-box-fill'
    $content = $content -replace 'fas fa-truck', 'bi bi-truck'
    $content = $content -replace 'fas fa-layer-group', 'bi bi-layers-fill'
    $content = $content -replace 'fas fa-puzzle-piece', 'bi bi-puzzle-fill'
    $content = $content -replace 'fas fa-cube', 'bi bi-box-fill'
    $content = $content -replace 'fas fa-cubes', 'bi bi-boxes'
    $content = $content -replace 'fas fa-code', 'bi bi-code'
    $content = $content -replace 'fas fa-terminal', 'bi bi-terminal-fill'
    $content = $content -replace 'fas fa-bug', 'bi bi-bug-fill'
    $content = $content -replace 'fas fa-tasks', 'bi bi-list-task'
    $content = $content -replace 'fas fa-check-square', 'bi bi-check-square-fill'
    $content = $content -replace 'fas fa-square', 'bi bi-square-fill'
    $content = $content -replace 'fas fa-dot-circle', 'bi bi-record-circle-fill'
    $content = $content -replace 'fas fa-circle', 'bi bi-circle-fill'
    $content = $content -replace 'fas fa-plus-square', 'bi bi-plus-square-fill'
    $content = $content -replace 'fas fa-minus-square', 'bi bi-dash-square-fill'
    $content = $content -replace 'fas fa-minus-circle', 'bi bi-dash-circle-fill'
    $content = $content -replace 'fas fa-minus', 'bi bi-dash-lg'
    $content = $content -replace 'fas fa-exclamation', 'bi bi-exclamation-lg'
    $content = $content -replace 'fas fa-question-circle', 'bi bi-question-circle-fill'
    $content = $content -replace 'fas fa-question', 'bi bi-question-lg'
    $content = $content -replace 'fas fa-info', 'bi bi-info-lg'
    $content = $content -replace 'fas fa-lightbulb', 'bi bi-lightbulb-fill'
    $content = $content -replace 'fas fa-eye', 'bi bi-eye-fill'
    $content = $content -replace 'fas fa-eye-slash', 'bi bi-eye-slash-fill'
    $content = $content -replace 'fas fa-search-plus', 'bi bi-zoom-in'
    $content = $content -replace 'fas fa-search-minus', 'bi bi-zoom-out'
    $content = $content -replace 'fas fa-expand', 'bi bi-arrows-fullscreen'
    $content = $content -replace 'fas fa-compress', 'bi bi-fullscreen-exit'
    $content = $content -replace 'fas fa-expand-arrows-alt', 'bi bi-arrows-move'
    $content = $content -replace 'fas fa-arrows-alt', 'bi bi-arrows-move'
    $content = $content -replace 'fas fa-random', 'bi bi-shuffle'
    $content = $content -replace 'fas fa-retweet', 'bi bi-arrow-repeat'
    $content = $content -replace 'fas fa-history', 'bi bi-clock-history'
    $content = $content -replace 'fas fa-stopwatch', 'bi bi-stopwatch-fill'
    $content = $content -replace 'fas fa-hourglass-half', 'bi bi-hourglass-split'
    $content = $content -replace 'fas fa-hourglass-end', 'bi bi-hourglass-bottom'
    $content = $content -replace 'fas fa-glass-cheers', 'bi bi-cup-straw'
    $content = $content -replace 'fas fa-utensils', 'bi bi-cup-hot-fill'
    $content = $content -replace 'fas fa-coffee', 'bi bi-cup-fill'
    $content = $content -replace 'fas fa-hamburger', 'bi bi-hypnotize' 
    $content = $content -replace 'fas fa-pizza-slice', 'bi bi-pie-chart-fill'
    $content = $content -replace 'fas fa-beer', 'bi bi-cup-fill'
    $content = $content -replace 'fas fa-wine-glass', 'bi bi-cup-straw'
    $content = $content -replace 'fas fa-cocktail', 'bi bi-cup-straw'
    $content = $content -replace 'fas fa-smoking', 'bi bi-cloud-haze2'
    $content = $content -replace 'fas fa-smoking-ban', 'bi bi-cloud-slash'
    $content = $content -replace 'fas fa-tree', 'bi bi-tree-fill'
    $content = $content -replace 'fas fa-leaf', 'bi bi-flower1'
    $content = $content -replace 'fas fa-fire', 'bi bi-fire'
    $content = $content -replace 'fas fa-water', 'bi bi-droplet-fill'
    $content = $content -replace 'fas fa-tint', 'bi bi-droplet-half'
    $content = $content -replace 'fas fa-snowflake', 'bi bi-snow'
    $content = $content -replace 'fas fa-sun', 'bi bi-brightness-high-fill'
    $content = $content -replace 'fas fa-moon', 'bi bi-moon-fill'
    $content = $content -replace 'fas fa-cloud', 'bi bi-cloud-fill'
    $content = $content -replace 'fas fa-cloud-sun', 'bi bi-cloud-sun-fill'
    $content = $content -replace 'fas fa-cloud-moon', 'bi bi-cloud-moon-fill'
    $content = $content -replace 'fas fa-cloud-rain', 'bi bi-cloud-rain-fill'
    $content = $content -replace 'fas fa-cloud-showers-heavy', 'bi bi-cloud-rain-heavy-fill'
    $content = $content -replace 'fas fa-bolt', 'bi bi-lightning-charge-fill'
    $content = $content -replace 'fas fa-wind', 'bi bi-wind'
    $content = $content -replace 'fas fa-smog', 'bi bi-cloud-haze-fill'
    $content = $content -replace 'fas fa-umbrella', 'bi bi-umbrella-fill'
    $content = $content -replace 'fas fa-plane', 'bi bi-airplane-fill'
    $content = $content -replace 'fas fa-car', 'bi bi-car-front-fill'
    $content = $content -replace 'fas fa-bus', 'bi bi-bus-front-fill'
    $content = $content -replace 'fas fa-train', 'bi bi-train-front-fill'
    $content = $content -replace 'fas fa-subway', 'bi bi-train-front-fill'
    $content = $content -replace 'fas fa-bicycle', 'bi bi-bicycle'
    $content = $content -replace 'fas fa-motorcycle', 'bi bi-bicycle'
    $content = $content -replace 'fas fa-ship', 'bi bi-water'
    $content = $content -replace 'fas fa-space-shuttle', 'bi bi-rocket-fill'
    $content = $content -replace 'fas fa-rocket', 'bi bi-rocket-fill'
    $content = $content -replace 'fas fa-ambulance', 'bi bi-truck-front-fill'
    $content = $content -replace 'fas fa-hospital', 'bi bi-hospital-fill'
    $content = $content -replace 'fas fa-stethoscope', 'bi bi-bandaid-fill'
    $content = $content -replace 'fas fa-heartbeat', 'bi bi-heart-pulse-fill'
    $content = $content -replace 'fas fa-pills', 'bi bi-capsule'
    $content = $content -replace 'fas fa-prescription', 'bi bi-file-medical-fill'
    $content = $content -replace 'fas fa-wheelchair', 'bi bi-person-wheelchair'
    $content = $content -replace 'fas fa-blind', 'bi bi-person-walking'
    $content = $content -replace 'fas fa-deaf', 'bi bi-ear-fill'
    $content = $content -replace 'fas fa-sign-language', 'bi bi-hands'
    $content = $content -replace 'fas fa-tools', 'bi bi-tools'
    $content = $content -replace 'fas fa-gavel', 'bi bi-hammer'
    $content = $content -replace 'fas fa-balance-scale', 'bi bi-scales'
    $content = $content -replace 'fas fa-graduation-cap', 'bi bi-mortarboard-fill'
    $content = $content -replace 'fas fa-book', 'bi bi-book-fill'
    $content = $content -replace 'fas fa-book-open', 'bi bi-book-half'
    $content = $content -replace 'fas fa-clipboard', 'bi bi-clipboard-fill'
    $content = $content -replace 'fas fa-pen', 'bi bi-pen-fill'
    $content = $content -replace 'fas fa-mouse-pointer', 'bi bi-cursor-fill'

    # Regular (far)
    $content = $content -replace 'far fa-calendar-alt', 'bi bi-calendar-event'
    $content = $content -replace 'far fa-clock', 'bi bi-clock'
    $content = $content -replace 'far fa-envelope', 'bi bi-envelope'
    $content = $content -replace 'far fa-user', 'bi bi-person'
    $content = $content -replace 'far fa-check-circle', 'bi bi-check-circle'
    $content = $content -replace 'far fa-times-circle', 'bi bi-x-circle'
    $content = $content -replace 'far fa-edit', 'bi bi-pencil-square'
    $content = $content -replace 'far fa-trash-alt', 'bi bi-trash'
    $content = $content -replace 'far fa-save', 'bi bi-floppy'
    $content = $content -replace 'far fa-folder', 'bi bi-folder'
    $content = $content -replace 'far fa-folder-open', 'bi bi-folder2-open'
    $content = $content -replace 'far fa-file', 'bi bi-file-earmark'
    $content = $content -replace 'far fa-file-alt', 'bi bi-file-earmark-text'
    $content = $content -replace 'far fa-image', 'bi bi-image'
    $content = $content -replace 'far fa-comment', 'bi bi-chat'
    $content = $content -replace 'far fa-comments', 'bi bi-chat-text'
    $content = $content -replace 'far fa-heart', 'bi bi-heart'
    $content = $content -replace 'far fa-star', 'bi bi-star'
    $content = $content -replace 'far fa-bell', 'bi bi-bell'
    $content = $content -replace 'far fa-bookmark', 'bi bi-bookmark'
    $content = $content -replace 'far fa-eye', 'bi bi-eye'
    $content = $content -replace 'far fa-eye-slash', 'bi bi-eye-slash'
    $content = $content -replace 'far fa-copy', 'bi bi-clipboard'
    $content = $content -replace 'far fa-clipboard', 'bi bi-clipboard'

    if ($content -ne $original) {
        Set-Content $_.FullName -Value $content -NoNewline
        $updates++
        Write-Host "Migrated => " $_.FullName
    }
}
Write-Host "`nTotal files migrated: $updates"
