# Generated by Django 6.0.1 on 2026-01-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='default_description',
            field=models.TextField(),
        ),
    ]
