# Generated by Django 6.0.3 on 2026-03-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_sessionspeaker_speaking_duration_and_more'),
        ('organizers', '0003_alter_eventtemplate_default_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerteammember',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='organizer_team_members', to='events.event'),
        ),
    ]
