# Generated by Django 6.0.3 on 2026-03-13 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_ticketpurchase_ticket_ticketanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='assigned_ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.tickettype'),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_bulk_rows', to='registration.registration'),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='mapped_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bulkregistrationrow',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='current_step',
            field=models.CharField(choices=[('uploaded', 'File Uploaded'), ('mapped', 'Columns Mapped'), ('validated', 'Data Validated'), ('configured', 'Options Configured'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='default_ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads', to='registration.tickettype'),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='detected_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='error_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='import_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='valid_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='validation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bulkregistrationupload',
            name='warning_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulkregistrationrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkImportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('upload', 'File Uploaded'), ('mapping', 'Columns Mapped'), ('validation', 'Data Validated'), ('configuration', 'Options Configured'), ('execution', 'Import Executed'), ('completion', 'Import Completed'), ('error', 'Error Occurred')], max_length=20)),
                ('action_details', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('result_summary', models.TextField(blank=True)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='registration.bulkregistrationupload')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
