# Generated by Django 6.0.3 on 2026-03-13 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_bulkregistrationrow_assigned_ticket_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='purchaser',
            field=models.ForeignKey(blank=True, help_text='The user who bought/created this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
