# Generated by Django 6.0.3 on 2026-03-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_registration_purchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of tickets purchased'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted'), ('checked_in', 'Checked In'), ('refunded', 'Refunded')], default='confirmed', max_length=20),
        ),
    ]
