# Generated by Django 6.0.2 on 2026-03-03 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0001_initial'),
        ('events', '0002_rename_speaker_eventsession_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['event', 'status'], name='advanced_ta_event_i_f5cc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='advanced_ta_assigne_57fe96_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='advanced_ta_due_dat_e4ba6e_idx'),
        ),
    ]
