# Generated by Django 6.0.3 on 2026-03-14 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0002_alter_task_options_task_actual_hours_task_attachment_and_more'),
        ('events', '0005_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_password', models.CharField(max_length=128)),
                ('password_set_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usher_assignments', to='events.event')),
                ('locations', models.ManyToManyField(related_name='ushers', to='events.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
