# Generated by Django 6.0.3 on 2026-03-14 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0003_usherassignment'),
        ('events', '0005_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usherassignment',
            name='venue_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='usherassignment',
            name='locations',
        ),
        migrations.AlterUniqueTogether(
            name='usherassignment',
            unique_together={('user', 'event', 'venue_name')},
        ),
    ]
