# Generated by Django 6.0.2 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0004_alter_usherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('usher', 'Usher'), ('attendee', 'Attendee')], max_length=30),
        ),
    ]
