# Generated by Django 6.0.2 on 2026-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0005_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('coordinator', 'Coordinator'), ('usher', 'Usher'), ('attendee', 'Attendee')], max_length=30),
        ),
    ]
