# Generated by Django 6.0.1 on 2026-02-21 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_speaker_eventsession_tags_and_more'),
        ('registration', '0002_promocode_discount_type_promocode_max_uses_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendeeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_messages', to='events.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='registration.registration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('speaker', 'Speaker'), ('staff', 'Staff'), ('sponsor', 'Sponsor'), ('vip_speaker', 'VIP Speaker')], default='standard', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('qr_code_data', models.CharField(blank=True, max_length=255)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_printed', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='registration.registration')),
            ],
            options={
                'ordering': ['registration__event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual Entry'), ('kiosk', 'Kiosk'), ('self', 'Self Check-in')], default='manual', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_records_made', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='registration.registration')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='registration_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration.registrationfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration.registration')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_topics', models.JSONField(blank=True, default=list)),
                ('preferred_tracks', models.JSONField(blank=True, default=list)),
                ('dietary_requirements', models.JSONField(blank=True, default=list)),
                ('dietary_notes', models.TextField(blank=True)),
                ('accessibility_needs', models.JSONField(blank=True, default=list)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('networking_enabled', models.BooleanField(default=True)),
                ('networking_bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('saved_sessions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_preferences', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='registration.registration')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.eventsession')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('registration', 'session')},
            },
        ),
    ]
